version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379

  django:
    build: .
    command: bash -c "chmod +x ./scripts/*.sh && ./scripts/start.sh django"
    ports:
      - 8000:8000
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  celery-beat:
    build: .
    command: bash -c "chmod +x ./scripts/*.sh && ./scripts/start.sh celery-beat"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis

  flower:
    build: .
    command: celery flower
    ports:
      - 5555:5555
    env_file:
      - .env
    depends_on:
      - redis
      - web
      - worker_beat

volumes:
  db_data:
